- CTP/sql/src/com/navercorp/cubridqa/cqt/webconsole/Starter.java
- CTP/sql/src/com/navercorp/cubridqa/cqt/webconsole/SummaryModel.java
There are two sub issues:  
a. webconsole can not start successfully on some windows platform
b. test results can't be shown in web page correctly due to "msg_id" property in summary_info file.
Provided patch fix them.
> [CUBRIDQA-6] fix web console cannot start and show results

- CTP/README.md
- CTP/conf/medium.conf
- CTP/conf/sql.conf
- CTP/sql/bin/run.sh
re-recreate a pull request to commit change into develop branch, the hot-fix includes bugs 1, 2, 3 from CUBRIDQA-6
> [CUBRIDQA-6] fix port problems and platform compatibility problems

- CTP/sql/bin/run.sh
Dear Fan,
I correct the syntax of run.sh, please review it. 
thanks
> [CUBRIDQA-6] fix syntax error in script

- CTP/sql/bin/run.sh
Dear fan,
I change the memory size for java options, please review it. 
thanks
> [CUBRIDQA-6] decrease the memory for windows platform

- CTP/sql/bin/run_memory.sh
- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
- CTP/sql/memory/default.supp
Dear Fan,
I added memory leak testing component into CTP, please review it. any concerns please tell me.
thanks
> [CUBRIDQA-6] add memory component into CTP

- CTP/sql/bin/run.sh
Dear Fan,
I fix one bug when global variable can't be set correctly from subshell. please review it. thanks
> [CUBRIDQA-15] fix vairable setting from subshell to its parent shell

- CTP/sql/bin/run.sh
remove unneeded variables from script
> [CUBRIDQA-15] delete unneeded variables from run.sh

- CTP/sql/memory/default.supp
@fanzaiqiang 
I added the memory leak error which is not a bug into suppression file of memory leak, please review it.
> [CBRD-20194] filter memory leak error into suppression accordingly

- CTP/sql/bin/interactive.sh
- CTP/sql/bin/run.sh
- CTP/sql/bin/run_memory.sh
@fanzaiqiang 
I restructure scripts and remove the duplicated copyright, please ignore the last pull request, and review this one
> [CUBRIDQA-26] add interactive mode and remove the duplicated copyright

- CTP/README.md
@fanzaiqiang 
I added interactive feature instruction into readme file, please review it. thanks
> [CUBRIDQA-26] add interactive mode into readme file

- CTP/sql/src/com/navercorp/cubridqa/cqt/console/util/TestUtil.java
@fanzaiqiang 
I changed ctp to use default build number format
> [CUBRIDQA-31] fix ctp to use original build number format

- CTP/sql/bin/interactive.sh
@fanzaiqiang 
make ctp support interactive mode on windows, please review it. thanks
> [CUBRIDQA-26] make ctp support interactive mode on windows

- CTP/sql/bin/run.sh
@fanzaiqiang 
add --posix parameter for bash to support windows platform
> [CUBRIDQA-26] add --posix for bash to support windows prompt

- CTP/sql/bin/interactive.sh
- CTP/sql/src/com/navercorp/cubridqa/cqt/console/util/TestUtil.java
@fanzaiqiang 
add two number data for result folder to avoid the folder names are duplicated, please review it. thanks
> [CUBRIDQA-4] add two random data to avoid result folders are duplicated

- CTP/common/script/start_consumer.sh
@fanzaiqiang 
refine cubrid_scheduler to support function parameter for exec, please review it. thanks
> [CUBRIDQA-33] enhance ctp to support function parameter for exec

- CTP/common/sched/init.sh
- CTP/common/script/start_consumer.sh
@fanzaiqiang 
fix environment problem in different sub shell, please review it. thanks
> [CUBRIDQA-33] fix environment variables problem in different sub shell

- CTP/shell/src/com/navercorp/cubridqa/shell/common/SSHConnect.java
- CTP/shell/src/com/navercorp/cubridqa/shell/common/ShellInput.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployOneNode.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseGithub.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseSVN.java
- CTP/shell/src/com/navercorp/cubridqa/shell/dispatch/Dispatch.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/Context.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/Test.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/TestMonitor.java
- CTP/shell/src/com/navercorp/cubridqa/shell/result/FeedbackFile.java
@fanzaiqiang 
I fix configuration file problem for service protocol, please review it. thanks
> [CUBRIDQA-33] fix configuration file problem for service protocol

- CTP/common/script/start_consumer.sh
@fanzaiqiang 
refine continue mode for start_consumer and remove function mode feature. please review it.
thanks
> [CUBRIDQA-40] refine continue mode and remove unneeded scripts

- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployOneNode.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/Context.java
@fanzaiqiang 
implement ctp upgrade on each node, please review it. thanks
> [CUBRIDQA-40] implement upgrade on each node for ctp

- CTP/common/sched/src/com/navercorp/cubridqa/scheduler/consumer/ObserverMessage.java
@fanzaiqiang 
handle build version when it is made by cmake, please review it. thanks
> [CUBRIDQA-37] handle build version when it is made by cmake

- CTP/shell/init_path/commonforc/src/commfunction.c
- CTP/shell/init_path/commonforjdbc_src/TestDbInfo.java
- CTP/shell/init_path/make_ha.sh
- CTP/shell/src/com/navercorp/cubridqa/shell/common/Constants.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/Deploy.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployHA.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployOneNode.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseGithub.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseSVN.java
- CTP/shell/src/com/navercorp/cubridqa/shell/dispatch/Dispatch.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/Context.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/Test.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/TestMonitor.java
- CTP/shell/src/com/navercorp/cubridqa/shell/result/FeedbackFile.java
@fanzaiqiang 
commit the first version for port configuration and update
> [CUBRIDQA-40] add port configuration and update

- CTP/common/ext/run_shell.sh
- CTP/shell/init_path/init.sh
@fanzaiqiang 
add new script for shell testing based on ctp, please review it. thanks
> [CUBRIDQA-40] add run_shell script based on CTP

- CTP/common/ext/run_shell.sh
- CTP/shell/src/com/navercorp/cubridqa/shell/common/ShellInput.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployHA.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseGithub.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseSVN.java
- CTP/shell/src/com/navercorp/cubridqa/shell/main/TestFactory.java
- CTP/shell/src/com/navercorp/cubridqa/shell/result/FeedbackDB.java
@fanzaiqiang 
remove feedback from run_shell script and remove HA.properties modification
> [CUBRIDQA-40] remove feedback from run_shell script and remove HA.properties modification

- CTP/common/script/start_consumer.sh
fix invalid path problem for continue mode
> [CUBRIDQA-40] fix path bug  for continue mode

- CTP/common/ext/run_shell.sh
- CTP/common/sched/init.sh
- CTP/common/script/start_consumer.sh
@fanzaiqiang 
refine continue mode script, please review it.
> [CUBRIDQA-40] fix continue mode problem since build_is_from_git does not exist

- CTP/common/ext/run_sql.sh
- https://github.com/CUBRID/cubrid-testtools/pull/89/commits/f22c23bf3276edf23605567437b10863812698e3
-- Rename action file name. I think it needn't to distinguish legacy and git.
-- Fix bug, get the correct result log path.
- https://github.com/CUBRID/cubrid-testtools/pull/89/commits/ae1bd98c7c28e478082ba393326ee69a1d4a66e0
-- Fix bug, create the correct the core_dirname. ( The jira issue number should be CUBRIDQA-45.)
> [CUBRIDQA-33][CUBRIDQA-45] fix bugs, correct result log path and core_dirname.

- CTP/common/ext/run_shell.sh
- CTP/shell/init_path/init.sh
- CTP/shell/src/com/navercorp/cubridqa/shell/common/CommonUtils.java
- CTP/shell/src/com/navercorp/cubridqa/shell/result/FeedbackFile.java
@fanzaiqiang 
fix some issues for generating package
> [CUBRIDQA-40] fix bugs for generating package for testing log

- CTP/common/src/com/navercorp/cubridqa/common/SFTPUpload.java
- CTP/shell/init_path/make_ha.sh
fix blankspace for ha variable and fix bug when upload target is file
> [CUBRIDQA-40] remove blankspace for ha variables and fix bug for ha setup

- CTP/common/script/start_consumer.sh
change log directory and add set -x for debug info
> [CUBRIDQA-40] change log directory and add debug info

- CTP/common/ext/run_shell.sh
- CTP/common/script/run_cubrid_install
@fanzaiqiang 
to support unit build
> [CBRD-20404] enhance run_cubrid_install to support unit testing build

- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployOneNode.java
@fanzaiqiang 
export ctp bin and script for run_cubrid_install and ini
> [CUBRIDQA-40] export ctp bin and script path for run_cubrid_install and ini

- CTP/shell/src/com/navercorp/cubridqa/shell/main/Main.java
@fanzaiqiang 
enhance ctp to identify bit version for unittest
> [CUBRIDQA-4] enhance CTP to identify bit for unittest

- CTP/common/ext/run_unittest.sh
- CTP/shell/local/unittest.sh
Modify test tool to support unit test.
(1). Add run_unittest.sh file to build and modify configuration parameters for daily regression test.
(2). Modify unittest.sh to check the test results.
> [CUBRIDQA-40] modify test tool to support unit test

- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployOneNode.java
@fanzaiqiang 
fix environment variables problems
> [CUBRIDQA-40] fix environment variables problems

- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployHA.java
> [CUBRIDQA-4] add copyright for DeplyHA.java

- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/DeployOneNode.java
- CTP/shell/src/com/navercorp/cubridqa/shell/deploy/TestCaseGithub.java
@fanzaiqiang 
fix case update problem and print run_git_update logs
> [CUBRIDQA-40] fix case update problem and print run_git_update logs

- CTP/README.md
@fanzaiqiang 
add readme for shell configuration and testing
> [CUBRIDQA-40] add readme for shell configuration and testing

- CTP/README.md
- CTP/conf/shell.conf
- CTP/conf/shell_agent.conf
@fanzaiqiang 
add comment for parameters in shell conf
> [CUBRIDQA-40] comment for shell configuration file

- CTP/common/ext/run_isolation.sh
@fanzaiqiang 
add 1st draft script for isolation testing
> [CUBRIDQA-40] add run_isolation script for isolation testing

- CTP/README.md
- CTP/conf/isolation.conf
- CTP/conf/shell.conf
@fanzaiqiang 
add readme for isolation
> [CUBRIDQA-53] add isolation testing readme into ctp

- CTP/common/ext/run_ha_repl.sh
@fanzaiqiang 
add run_ha_repl for replication testing
> [CUBRIDQA-55] add run_ha_repl script for  ha_repl testing

- CTP/common/ext/run_ha_repl.sh
- CTP/common/script/run_svn_update
@fanzaiqiang 
add case update for ha_repl and run_svn_update interface
> [CUBRIDQA-55] add case update script and svn case update interface

- CTP/common/ext/run_ha_repl.sh
@fanzaiqiang 
remove case update for continue mode
> [CUBRIDQA-55] remove case update for continue mode

- CTP/common/ext/run_ha_repl.sh
@fanzaiqiang 
correct the logic of configuration update and case path
> [CUBRIDQA-55] correct logic for updating configuration file and case path

- CTP/common/ext/run_sql_by_cci.sh
@fanzaiqiang 
add the first version for schd to call sql_by_cci
> [CUBRIDQA-58] add run_sql_by_cci for schd call

- CTP/sql/bin/run.sh
- CTP/sql_by_cci/compile.sh
- CTP/sql_by_cci/execute.c
@fanzaiqiang 
fix some bugs for case path and compile
> [CUBRIDQA-58] fix bugs for case path and compile

- CTP/common/ext/run_sql_by_cci.sh
- CTP/sql/bin/run.sh
- CTP/sql_by_cci/ccqt.c
@fanzaiqiang 
fix log folder make and category during testing
> [CUBRIDQA-58] fix log folder make and category

- CTP/sql_by_cci/ccqt.c
- CTP/sql_by_cci/compile.sh
@fanzaiqiang 
fix crash and print compile information
> [CUBRIDQA-58] fix crash and print compile info

- CTP/README.md
- CTP/conf/ha_repl.conf
@fanzaiqiang 
add ha_repl readme
> [CUBRIDQA-55] add readme for ha_repl

- CTP/sql/bin/run.sh
@fanzaiqiang 
correct bit value for result
> [CUBRIDQA-58] fix bit value for result

- CTP/sql/bin/run.sh
@fanzaiqiang 
convert the first letter of os to lower
> [CUBRIDQA-58] convert the first letter of os to lower

- CTP/common/ext/run_sql_by_cci.sh
@fanzaiqiang 
correct ccqt home and refine scenario type compatibility
> [CUBRIDQA-58] correct ccqt home and refine scenario type compatibility

- CTP/common/script/start_consumer.sh
enhance ctp to support at on windows
> [CUBRIDQA-4] enhance ctp to support at on windows

- CTP/common/script/start_consumer.sh
refine auto update for windows platform
> [CUBRIDQA-4] refine auto update for windows platform

- CTP/sql/bin/run.sh
@fanzaiqiang 
correct total testing number name
> [CUBRIDQA-58] correct total testing number name

- CTP/README.md
@fanzaiqiang 
refine sql_by_cci readme to keep same style with others
> [CUBRIDQA-58] refine readme for sql_by_cci to keep same style with sql/shell/isolation/ha_repl

- CTP/README.md
- CTP/conf/ha_repl.conf
- CTP/conf/isolation.conf
- CTP/conf/shell.conf
@fanzaiqiang 
refine readme for syntax and to make it more clear
> [CUBRIDQA-55] refine readme for syntax and to make it more clear

- CTP/common/ext/run_jdbc.sh
@fanzaiqiang 
add run_jdbc.sh for daily regression
> [CUBRIDQA-60] add run_jdbc for daily regression

- CTP/common/ext/run_jdbc.sh
@fanzaiqiang 
correct one script for variable
> [CUBRIDQA-60] Fix jdbc bugs in run_jdbc.sh script

- CTP/README.md
@fanzaiqiang 
please review jdbc unit test manual, thanks
> [CUBRIDQA-60] add jdbc unit test manual

- CTP/README.md
@fanzaiqiang 
refine jdbc manual format
> [CUBRIDQA-60] refine jdbc manual format

- CTP/shell/init_path/recovery_ignore_item.conf
Add new ignore item in configuration file.
> [CUBRIDQA-66] add new ignore item in configuration file

- CTP/conf/jdbc.conf
- CTP/jdbc/bin/run.sh
@fanzaiqiang 
fix one typo when reading jdbc configuration file
> [CUBRIDQA-60] fix read jdbc configuration file section typo

- CTP/jdbc/bin/run.sh
@fanzaiqiang 
let testing quit when jdbc compile fail
> [CUBRIDQA-71] let testing quit when jdbc compile fail

- CTP/common/ext/run_shell.sh
@fanzaiqiang 
to support legacy daily regression for shell fm
> [CUBRIDQA-72] to support legacy regression for shell fm

- CTP/common/ext/run_sql.sh
@fanzaiqiang 
to support memory leak test from run_sql.sh
> [CUBRIDQA-72] to support memory leak test from run_sql.sh

- CTP/common/ext/run_ha_repl.sh
- CTP/common/ext/run_shell.sh
@fanzaiqiang 
to support disk checking for shell and ha_repl
> [CUBRIDQA-72] to support run action for shell and ha_repl

- CTP/conf/ha_repl.conf
- CTP/conf/isolation.conf
- CTP/conf/shell.conf
@fanzaiqiang 
updated the open parameter into conf
> [CUBRIDQA-71] add all open parameter for reference

- CTP/README.md
@fanzaiqiang 
update readme for shell and isolation regarding single instance and multiple instance
> [CUBRIDQA-71] update readme for single and multiple test

- CTP/common/ext/run_coverage.sh
- CTP/common/script/run_coverage_collect_and_upload
- CTP/common/script/run_cubrid_install
@fanzaiqiang 
add the first version script for coverage
> [CUBRIDQA-73] add coverage script

- CTP/common/ext/run_coverage.sh
@fanzaiqiang 
fix coverage package names problem for the different server
> [CUBRIDQA-73] fix coverage package names for the different server

- CTP/common/ext/run_coverage.sh
- CTP/common/script/run_cubrid_install
@fanzaiqiang 
remove the subfolder for the coverage source directory
> [CUBRIDQA-73] remove the subfolder for the coverage source directory

- CTP/common/ext/run_coverage.sh
- CTP/common/script/run_coverage_collect_and_upload
modify the permission of gcov and correct path of gcov
> [CUBRIDQA-73] modify the permission of gcov and correct path of gcov

- CTP/common/ext/run_coverage.sh
@fanzaiqiang 
correct the path of conf file
> [CUBRIDQA-73] correct the path of conf file

- CTP/common/script/run_coverage_collect_and_upload
> [CUBRIDQA-73] fix alias can't work problem

- CTP/common/ext/run_coverage.sh
- CTP/common/script/run_coverage_collect_and_upload
@fanzaiqiang 
update the packages name of the coverage build and use the default pwd
> [CUBRIDQA-73] update the packages name of the coverage build and use the default pwd

- CTP/common/ext/run_coverage.sh
@fanzaiqiang 
correct parameter name for coverage_controller_cc4c_home
> [CUBRIDQA-73] correct parameter name for coverage_controller_cc4c_home

- CTP/common/ext/run_coverage.sh
- CTP/common/script/run_coverage_collect_and_upload
- CTP/common/script/run_cubrid_install
@fanzaiqiang 
try to merge the enhancement for the coverage automation
> [CUBRIDQA-73] enhance the coverage testing script 

- CTP/common/ext/run_coverage.sh
@fanzaiqiang 
add databases folder as default
> [CUBRIDQA-73] add databases folder as default

- CTP/common/script/run_coverage_collect_and_upload
@fanzaiqiang 
to support proxy for run_coverage_collect_and_upload
> [CUBRIDQA-73] use proxy to avoid the permissin deny

- CTP/shell/init_path/init.sh
- CTP/shell/init_path/rqg_init.sh
@fanzaiqiang 
add rqg init file
> [CUBRIDQA-74] add rqg init file

- CTP/shell/init_path/init.sh
add some checks for the input parameters for compare_result_between_files
> [CUBRIDQA-143] add some checks for the input parameters for compare_result_between_files

- CTP/shell/init_path/init.sh
correct a mistake in compare_result_between_files
> [CUBRIDQA-143] correct a mistake in compare_result_between_files

- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
add track origins option for memory test
> [CUBRIDQA-147] add track origins option for memory test

- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
refine memory mock code to check process restart
> [CUBRIDQA-147] refine memory mock code to check process restart

- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
change memory result output format as log
> [CUBRIDQA-147] change memory result output format as log

- CTP/sql/memory/cub_server.c
remove parameter for memory leak
> [CUBRIDQA-147] remove parameter for memory leak

- CTP/sql/bin/run_memory.sh
fix invalid cp when testing fail
> [CUBRIDQA-147] fix invalid cp when testing fail

- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
exclude --expensive-definedness-checks=yes parameter from dailyqa
http://jira.cubrid.org/browse/CUBRIDQA-167
> [CUBRIDQA-167] exclude --expensive-definedness-checks=yes parameter from dailyqa

- CTP/sql/bin/run_memory.sh
- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
backup cubrid log and add date time for call stack
> [CUBRIDQA-167] backup cubrid log and add date time for call stack

- CTP/common/script/run_git_update
fix git lock to cause update fail
http://jira.cubrid.org/browse/CUBRIDQA-170
> [CUBRIDQA-170] fix git lock to cause update fail

- CTP/shell/init_path/init.sh
http://jira.cubrid.org/browse/CUBRIDQA-182
> [CUBRIDQA-182] try more times for make_tz.bat

- CTP/sql/bin/run.sh
This  removes carriage return character which is not necessary in windows
> [CUBRIDQA-163] modify run.sh to generate correctly mdb_qa.xml in windows with cygwin64

- CTP/common/script/run_cubrid_install
fix run_cubrid_isntall bug for the compatibility testing
> [CUBRIDQA-77] fix cubrid compatibility installation bug

- CTP/common/script/run_git_update
> [CUBRIDQA-207] update to delete branch name

- CTP/common/ext/run_compat_cci.sh
Deploy cci compatibility test with the latest CTP
server version>=10.0,test it with CTP.
server version <10.0 ,test it with CQT
> [CUBRIDQA-77] deploy cci compatibility with CTP

- CTP/common/ext/run_compat_jdbc.sh
1. merge run_compat_jdbc_svr_linux.sh and run_compat_jdbc_drv_linux.sh  to run_compat_jdbc.sh
2. refine some test code
> [CUBRIDQA-77] deploy jdbc compatibility test with CTP

- CTP/common/ext/run_compat_cci.sh
use run_svn_update common function to update cases
> [CUBRIDQA-77] use run_svn_update common function

- CTP/common/script/analyze_failure.sh
http://jira.cubrid.org/browse/CUBRIDQA-216
> [CUBRIDQA-216] fix report issue fail bug

- CTP/shell/init_path/init.sh
http://jira.cubrid.org/browse/CUBRIDQA-285
> [CUBRIDQA-285] refactor the OS variable in init.sh

- CTP/shell/init_path/init.sh
add alias for awk and diff command for windows shell test
refer to http://jira.cubrid.org/browse/CUBRIDQA-149
> [CUBRIDQA-149] add alias for awk and diff command for windows shell test

- CTP/shell/init_path/rqg_init.sh
please refer to cubrid-testcases-private/random_query_generator/_03_mvcc/recovery/util.sh
> [CUBRIDQA-74] add some functions for backup, log checking

- CTP/shell/init_path/rqg_init.sh
> [CUBRIDQA-74] refine rqg init script

- CTP/README.md
update CTP manual for RQG testing
> [CUBRIDQA-74] update CTP manual for RQG testing

- CTP/common/script/analyze_failure.sh
fix report issue can't get core name problem
http://jira.cubrid.org/browse/CUBRIDQA-447
> [CUBRIDQA-447] fix report issue can't get core name problem

- CTP/sql/bin/interactive.sh
- CTP/sql/bin/run.sh
create result directory for sql_by_cci if it's not created
> [CUBRIDQA-451] create result dir for sql_by_cci

- CTP/shell/init_path/init_ext.sh
> [CUBRIDQA-431] cubrid_ha_create supports legacy build

- CTP/shell/init_path/init_ext.sh
http://jira.cubrid.org/browse/CUBRIDQA-540
> [CUBRIDQA-540]  use host pw with priority instead of default pw

- CTP/sql/memory/cub_cas.c
- CTP/sql/memory/cub_server.c
http://jira.cubrid.org/browse/CUBRIDQA-568
> [CUBRIDQA-568] enlarge --num-callers of valgrind

- CTP/shell/local/unittest.sh
http://jira.cubrid.org/browse/CUBRIDQA-655
> [CUBRIDQA-655] enhance unittest tool to avoid error was thrown

- CTP/common/script/run_cubrid_install
http://jira.cubrid.org/browse/CUBRIDQA-658
> [CUBRIDQA-658] fix CTP to print log in console and log file

- CTP/isolation/ctltool/runone.sh
http://jira.cubrid.org/browse/CUBRIDQA-670
upgrade format_ctl_result() for new test case cbrd_21900.ctl .
ref: https://github.com/CUBRID/cubrid-testcases/pull/408
> [CUBRIDQA-670]upgrade format_ctl_result() for new test case.

- CTP/shell/init_path/init_ext.sh
add function to format class oid output
> [CUBRIDQA-703] add function to format class oid output

- CTP/shell/local/unittest.sh
http://jira.cubrid.org/browse/CBRD-21611
> [CBRD-21611] get the unit test cases from bin or util directory

- CTP/shell/init_path/shell_utils.sh
refer to http://jira.cubrid.org/browse/CUBRIDQA-760
> [CUBRIDQA-760] fix core exclution

- CTP/sql/bin/run_memory.sh
http://jira.cubrid.org/browse/CUBRIDQA-764
Copy the console log to result folder to backup.
> [CUBRIDQA-764] backup console log.

- CTP/sql/memory/default.supp
http://jira.cubrid.org/browse/CUBRIDQA-775
> [CUBRIDQA-775]update suppress file.

- CTP/common/script/analyze_failure.sh
http://jira.cubrid.org/browse/CUBRIDQA-789
Fix unable to open issue automatically by clicking a button in QA homepage.
> [CUBRIDQA-789]  limit core stack with 30000

- CTP/sql/bin/run.sh
http://jira.cubrid.org/browse/CUBRIDQA-795
> [CUBRIDQA-795] add cubrid_rel, user, ip into main.info.

- CTP/common/script/kill_process_tree.sh
- CTP/common/script/killtree.sh
Add a common script to kill process tree.
http://jira.cubrid.org/browse/CUBRIDQA-803
Usage: sh killtree.sh <pid>
It will kill the process and it's child processes.
> [CUBRIDQA-803]add a common script to kill process tree.

- CTP/sql/memory/default.supp
http://jira.cubrid.org/browse/CUBRIDQA-775
Added suppress rule for CBRD-21967.
http://jira.cubrid.org/browse/CBRD-21967
> [CUBRIDQA-775] update suppress file.

- CTP/common/script/analyze_failure.sh
- CTP/shell/init_path/shell_utils.sh
http://jira.cubrid.org/browse/CUBRIDQA-867?focusedCommentId=4753998&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4753998
> [CUBRIDQA-867] correct login info to show gateway approach

- CTP/common/script/analyze_failure.sh
http://jira.cubrid.org/browse/CUBRIDQA-867
Fix a slip lead to unable to receive parameter.
> [CUBRIDQA-867] fix unable to receive parameter

- CTP/isolation/ctltool/runone.sh
http://jira.cubrid.org/browse/CUBRIDQA-889
http://jira.cubrid.org/browse/CBRD-22830
> [CUBRIDQA-889]remove full hostname before comparing answer and result.

- CTP/shell/init_path/make_ha_upper.sh
http://jira.cubrid.org/browse/CBRD-22830
https://github.com/CUBRID/cubrid/pull/1501
> [CBRD-22830]replace the canonical name too in format_hb_status

- CTP/common/ext/run_compat_jdbc.sh
1. modify code to save current used patch files
2.  before cp patch files,update test cases
refer to http://jira.cubrid.org/browse/CUBRIDQA-900
> [CUBRIDQA-900] before cp patch files,update test cases

- CTP/common/script/analyze_failure.sh
http://jira.cubrid.org/browse/CUBRIDQA-962
> [CUBRIDQA-962]Provide both public IP and private IP

- README.md
- doc/ctp_install_guide.md
http://jira.cubrid.org/browse/CUBRIDQA-831
This is CTP  installation guide which is general for all tests.
> [CUBRIDQA-831] ctp installation guide

- doc/memoryleak_guide.md
http://jira.cubrid.org/browse/CUBRIDORG-139
> [CUBRIDORG-139]change QA homepage url.

- doc/ctp_install_guide.md
http://jira.cubrid.org/browse/CUBRIDQA-831
add windows install guide
> [CUBRIDQA-831] update ctp_install_guide.md

- README.md
- doc/ctp_install_guide.md
- doc/jdbc_guide.md
- doc/shell_ext_guide.md
http://jira.cubrid.org/browse/CUBRIDQA-975
> [CUBRIDQA-975] shell_ext guide

- doc/code_coverage_guide.md
- doc/jdbc_guide.md
- doc/shell_ext_guide.md
- doc/unittest_guide.md
Correct incorrect link for CTP installation
> [CUBRIDQA-831] correct like to install CTP

- README.md
- doc/ctp_install_guide.md
- doc/shell_win_guide.md
http://jira.cubrid.org/browse/CUBRIDQA-981
> [CUBRIDQA-981] add win shell guide

- doc/cci_compatibility_guide.md
- doc/cci_guide.md
- doc/code_coverage_guide.md
- doc/ha_repl_guide.md
- doc/ha_shell_guide.md
- doc/isolation_guide.md
- doc/jdbc_compatibility_guide.md
- doc/jdbc_guide.md
- doc/memoryleak_guide.md
- doc/rqg_guide.md
- doc/shell_ext_guide.md
- doc/shell_guide.md
- doc/shell_heavy_guide.md
- doc/shell_long_guide.md
- doc/shell_win_guide.md
- doc/sql_guide.md
- doc/unittest_guide.md
> [CUBRIDQA-831] add title for each guide

- CTP/shell/init_path/init.sh
http://jira.cubrid.org/browse/CUBRIDQA-1027
> [CUBRIDQA-1027] temporarily revise function for line number

- CTP/shell/init_path/init.sh
http://jira.cubrid.org/browse/CUBRIDQA-1027
> [CUBRIDQA-1027] fix file name with a path issue
